apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: flux-terraform
  labels:
    provider: terraform
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: juvensys.com/v1alpha1
    kind: Flux
  # patchSets:
  #   - name: Common
  #     patches:
  #       - fromFieldPath: metadata.name
  #         toFieldPath: metadata.name
  resources:
    - name: terraform
      base:
        apiVersion: tf.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
          - filename: kubeconfig.yaml
            source: Secret
            secretRef:
              namespace: crossplane-system
              name: cluster-config
              key: kubeconfig
          configuration: |
            terraform {
              required_version = ">= 0.13"
              backend "kubernetes" {
              secret_suffix    = "state"
              config_path      = "kubeconfig.yaml"
            }
              required_providers {
                kubectl = {
                  source  = "gavinbunney/kubectl"
                  version = ">= 1.13.1"
                }
                flux = {
                  source  = "fluxcd/flux"
                  version = ">= 0.8.1"
                }
              }
            }
            provider "flux" {}
            provider "kubectl" {
              config_path = "kubeconfig.yaml"
            }
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
    - name: terraform-flux
      base:
        apiVersion: tf.crossplane.io/v1alpha1
        kind: Workspace
        spec:
          # providerConfigRef:
          #   name: flux-terraform
          forProvider:
            source: Inline
            module: |
              data "flux_install" "main" {
                target_path = "dev"
              }
              data "kubectl_file_documents" "docs" {
                content = data.flux_install.main.content
              }
              resource "kubectl_manifest" "test" {
                  count     = length(data.kubectl_file_documents.docs.documents)
                  yaml_body = element(data.kubectl_file_documents.docs.documents, count.index)
              }
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - fromFieldPath: spec.id
          toFieldPath: spec.providerConfigRef.name