apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: flux.juvensys.com
spec:
  defaultCompositionRef:
    name: flux-terraform
  group: juvensys.com
  names:
    kind: Flux
    plural: flux
  claimNames:
    kind: FluxClaim
    plural: fluxclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  flux_version:
                    description: The the flux version to install.
                    type: string
                    default: v0.24.1
                  image_registry:
                    description: Container registry where the toolkit images are published.
                    type: string
                    default: ghcr.io/fluxcd
                  image_pull_secret:
                    description: Kubernetes secret name used for pulling the toolkit images from a private registry.
                    type: string
                    default: ""
              kubeConfig:
                description: The Kubeconfig details.
                type: object
                properties:
                  secretNamespace:
                    description: Namespace of secret
                    type: string
                    default: crossplane-system
                  secretName:
                    description: secretName
                    type: string
                  secretKey:
                    description: secretKey
                    type: string
                    default: kubeconfig
            required:
            - kubeConfig